learning numpy from chai aur code

In [3]:

import numpy as np 

In [4]:
array_1d=np.array([1,2,3,4,5])
print("1d array is : ",array_1d)

1d array is :  [1 2 3 4 5]


### for creating a 2d array we should pass the array as one list

In [5]:
array_2d=np.array([[1,2,3,4],[0,8,8,7]])
print("2d array is: ",array_2d)

2d array is:  [[1 2 3 4]
 [0 8 8 7]]


### python list VS numpy array

In [6]:
py_list=[1,2,3,4,5]
print("mulitplication operation for python list: ",py_list*2)

np_array=np.array([1,2,3,4,5])
print("mulitplication operation for numpy array: ",np_array*2)

mulitplication operation for python list:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
mulitplication operation for numpy array:  [ 2  4  6  8 10]


In [7]:
import time

start=time.time()
py_list=[ i*2 for i in range(100000)]
print("python list operation time taken: ",time.time()-start)

start=time.time()
np_array=np.arange(100000)*2
print("numpy array operation time taken: ",time.time()-start)


python list operation time taken:  0.008279085159301758
numpy array operation time taken:  0.006798744201660156


### Creating numpy array from scratch
we should create array in same data types as well as matrices also

In [12]:
zeros=np.zeros((5,6))
print("zeros matrices: \n",zeros)

ones=np.ones((5,6))
print("ones matrices: \n",ones)

full=np.full((3,3),7)
print("full matrices: \n",full)

random=np.random.random((2,4))
print("random matrices: \n",random)

zeros=np.zeros((5,6))
print("zeros matrices: \n",zeros)

sequence=np.arange(0,20,2)
print("sequence matrices: \n",sequence)

zeros matrices: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
ones matrices: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
full matrices: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random matrices: 
 [[0.98783432 0.87972557 0.11377218 0.74090473]
 [0.96330925 0.22543299 0.57393437 0.6756847 ]]
zeros matrices: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
sequence matrices: 
 [ 0  2  4  6  8 10 12 14 16 18]


### vector VS matrices VS tensor

In [ ]:
vector =np.array([1,2,3,4])
print("vector:\n",vector)

matrix =np.array([[1,2,3,4],
                  [5,6,7,8]])
print("matrix:\n",matrix)

tensor=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[11,12,13]]
])
print("tensor:\n",tensor)

vector:
 [1 2 3 4]
matrix:
 [['1' '2' '3' '4']
 ['a' 'b' 'c' 'd']]
tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


### array properties

In [14]:
np_array=np.array([
    [1,2,3,4],
    [2,4,6,8]
])
print("size :",np_array.size)
print("shape :",np_array.shape)
print("dimansion :",np_array.ndim)
print("type :",np_array.dtype)

size : 8
shape : (2, 4)
dimansion : 2
type : int64


### array reshaping

In [23]:
arr = np.arange(12)
print("original array: ",arr)

reshaped =arr.reshape((3,4))
print("reshaped array:\n",reshaped)

flatted=reshaped.flatten()
print("flatten array:",flatted)

#ravel returns the views instead of copy
revel=reshaped.ravel()
print("ravel array:",revel)

transpose=reshaped.T
print("transpose of array:\n",transpose)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose of array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [1]:
import numpy as np

a= np.array([
    [1,2,3],
    [3,4,5]
             ])

a.shape

(2, 3)