## numpy learning phase 2 is array operatin


In [ ]:
import numpy as np

In [ ]:

arr=np.array([1,2,3,4,5,6,7])

print(arr)
print("basic slicing :",arr[2:5])
print("reverse slicing :",arr[::-1])
print("step slicing :",arr[1:6:3])
print("negative index slicing :",arr[-4:])

In [ ]:
arr_2d = np.array([[2,3,4],
                   [0,9,8],
                   [12,4,5]])
print(arr_2d)
print("shape of the array:",arr_2d.shape)
print("size of the array:",arr_2d.size)
print("specific element",arr_2d[2,2])
print("printing row:",arr_2d[2])
print("printing column:",arr_2d[:,2])

## Sorting


In [108]:
unsorted=np.array([4,3,1,6,3,2,6,9,232])

print("1d sorting:",np.sort(unsorted))

unsorted_2d=np.array([[4,3,1],[6,1,2],[1,9,2]])

print("2d sorting by column:",np.sort(unsorted_2d,axis=0))
print("2d sorting by row:",np.sort(unsorted_2d,axis=1))

1d sorting: [  1   2   3   3   4   6   6   9 232]
2d sorting by column: [[1 1 1]
 [4 3 2]
 [6 9 2]]
2d sorting by row: [[1 3 4]
 [1 2 6]
 [1 2 9]]


## Filtering

In [ ]:
numbers = np.array([32,2,1,5,2,5,2,6])

even_numbers=[numbers % 2==0]
print(even_numbers)


## filter with mask

In [51]:
mask=numbers>5
print("numbers greater than 5 :",mask,numbers[mask])

numbers greater than 5 : [ True False False False False False False  True] [32  6]


## Fancy indexing s np.where()

In [48]:
indexing = [0,5,2]
print("using indexing:",numbers[indexing])

whereing = np.where(numbers>2)

print("usng where:",whereing,numbers[whereing])

using indexing: [32  5  1]
usng where: (array([0, 3, 5, 7]),) [32  5  5  6]


In [60]:
condition_array=np.where(arr_2d>2,arr_2d*3,"")
print(condition_array)

[['' '9' '12']
 ['' '27' '24']
 ['36' '12' '15']]


## Adding and removing in array

In [ ]:
a=np.array([1,2,3,4])
b=np.array([11,22,33,44,55])
c=np.array([11,21,31,41])

print(np.concatenate((a,b,c)))

compatibily of arrays : False
[ 1  2  3  4 11 22 33 44 55 11 21 31 41]


## Array compatibility

In [77]:
print("compatibily of arrays :",a.shape==b.shape==c.shape)

compatibily of arrays : False


## Adding in 2d array in row wise and column wise

In [86]:
print(arr_2d)

new_row=([11,22,33])

array_with_row=np.vstack((arr_2d,new_row))

print("array with new row: \n",array_with_row)

new_col=([0],[0],[0],[0])
array_with_col=np.hstack((array_with_row,new_col))
print("array with new column: \n",array_with_col)


[[ 2  3  4]
 [ 0  9  8]
 [12  4  5]]
array with new row: 
 [[ 2  3  4]
 [ 0  9  8]
 [12  4  5]
 [11 22 33]]
array with new column: 
 [[ 2  3  4  0]
 [ 0  9  8  0]
 [12  4  5  0]
 [11 22 33  0]]


## Deleting Elements

In [107]:
print(arr)

deleted_1d=np.delete(arr,3)

print("Deleting element in 1d :",deleted_1d)

deleted_slice_1d=np.delete(arr,np.s_[3:6])

print("Deleting element in 1d :",deleted_slice_1d)


print("2d arr: \n",arr_2d)

deleted_2d = np.delete(arr_2d,2,1)

print("Deleting element in 2d : \n",deleted_2d)

[1 2 3 4 5 6 7]
Deleting element in 1d : [1 2 3 5 6 7]
Deleting element in 1d : [1 2 3 7]
2d arr: 
 [[ 2  3  4]
 [ 0  9  8]
 [12  4  5]]
Deleting element in 2d : 
 [[ 2  3]
 [ 0  9]
 [12  4]]
